apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedemoapp-deployment
  labels:
    app: kubedemoapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kubedemoapp
  template:
    metadata:
      labels:
        app: kubedemoapp
    spec:
      containers:
        - name: kubedemoapp
          image: bindusabavath/sample:kubeimage1   # Your Docker Hub image
          ports:
            - containerPort: 5000
