apiVersion: v1
kind: Service
metadata:
  name: kubedemoapp-service
spec:
  selector:
    app: kubedemoapp
  ports:
    - protocol: TCP
      port: 5000          # Service port inside cluster
      targetPort: 5000    # App port in container
      nodePort: 30080     # External access port on node
  type: NodePort
